config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :mytweets, as: "tweets"
  resources :mytweets
  resources :hashtags
  root 'hashtags#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  has_many :mytweets
  def image=(uploaded_io)
  File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
  end
  write_attribute(:image,uploaded_io.original_filename)
  end
  def image
  read_attribute(:image)
  end
end

app/models/mytweet.rb
class Mytweet < ActiveRecord::Base
  belongs_to :hashtag
  accepts_nested_attributes_for :hashtag
  attr_accessor :myhashtag
  before_validation :myfunc
  def myfunc
    if self.myhashtag.to_s.length > 0
      self.hashtag=Hashtag.find_or_initialize_by(name: "myhashtag")
    end
    tweet = Xclient.post("tweets", '{"text":"'+self.content+'"}')

    self.tweet_id=tweet["data"]["id"]
  end
end

app/models/user.rb
class User < ApplicationRecord
def mytweets
Tweet.where("content like ?","%#{pseudo}%")
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  before_action :set_hashtag, only: %i[ show edit update destroy ]

  # GET /hashtags or /hashtags.json
  def index
    @hashtags = Hashtag.all
  end

  # GET /hashtags/1 or /hashtags/1.json
  def show
    @tweets=@hashtag.mytweets
  end

  # GET /hashtags/new
  def new
    @hashtag = Hashtag.new
  end

  # GET /hashtags/1/edit
  def edit
  end

  # POST /hashtags or /hashtags.json
  def create
    @hashtag = Hashtag.new(hashtag_params)

    respond_to do |format|
      if @hashtag.save
        format.html { redirect_to hashtag_url(@hashtag), notice: "Hashtag was successfully created." }
        format.json { render :show, status: :created, location: @hashtag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hashtag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hashtags/1 or /hashtags/1.json
  def update
    respond_to do |format|
      if @hashtag.update(hashtag_params)
        format.html { redirect_to hashtag_url(@hashtag), notice: "Hashtag was successfully updated." }
        format.json { render :show, status: :ok, location: @hashtag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hashtag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hashtags/1 or /hashtags/1.json
  def destroy
    @hashtag.destroy

    respond_to do |format|
      format.html { redirect_to hashtags_url, notice: "Hashtag was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hashtag
      @hashtag = Hashtag.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hashtag_params
      params.require(:hashtag).permit(:name, :image)
    end
end

app/controllers/mytweets_controller.rb
class MytweetsController < ApplicationController
  before_action :set_mytweet, only: %i[ show edit update destroy ]

  # GET /mytweets or /mytweets.json
  def index
    @mytweets = Mytweet.all
  end

  # GET /mytweets/1 or /mytweets/1.json
  def show
  end

  # GET /mytweets/new
  def new
    @mytweet = Mytweet.new
  end

  # GET /mytweets/1/edit
  def edit
  end

  # POST /mytweets or /mytweets.json
  def create
    @mytweet = Mytweet.new(mytweet_params)

    respond_to do |format|
      if @mytweet.save
        format.html { redirect_to hashtag_url(@mytweet.hashtag), notice: "Mytweet was successfully created." }
        format.json { render :show, status: :created, location: @mytweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mytweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mytweets/1 or /mytweets/1.json
  def update
    respond_to do |format|
      if @mytweet.update(mytweet_params)
        format.html { redirect_to hashtag_url(@mytweet.hashtag), notice: "Mytweet was successfully updated." }
        format.json { render :show, status: :ok, location: @mytweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mytweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mytweets/1 or /mytweets/1.json
  def destroy
       mytweet=Xclient.delete("tweets/#{@mytweet.tweet_id}")
       p mytweet
       p mytweet['data']['deleted']
       p "tweet deleted"
             if mytweet["data"]["deleted"]
                       mymessage="le tweet a bien été supprimé sur twitter"
                                       @mytweet.destroy
                                             else
                                                     mymessage="le tweet n'a pas bien été supprimé sur twitter"
                                                           end


    respond_to do |format|
      format.html { redirect_to mytweets_url, notice: "Mytweet was successfully destroyed. #{mymessage}" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mytweet
      @mytweet = Mytweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mytweet_params
      params.require(:mytweet).permit(:content, :hashtag_id, :tweet_id,:myhashtag)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:fullname, :pseudo, :image)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
end

app/helpers/mytweets_helper.rb
module MytweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/hashtags/_form.html.erb
<%= form_with(model: hashtag) do |form| %>
  <% if hashtag.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(hashtag.errors.count, "error") %> prohibited this hashtag from being saved:</h2>

      <ul>
        <% hashtag.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/hashtags/_hashtag.html.erb
<div class="col">
  <%=link_to hashtag do%>
      <div class="card">
        <img src="/uploads/<%=hashtag.image%>" class="card-img-top" alt="...">
                    <div class="card-body">
                      <h5 class="card-title"><%=hashtag.name%></h5>
                      <%if params[:action] =="index" and params[:controller] == "hashtags"%>
                        <p class="card-text">  <%=link_to "edit this hashtg",edit_hashtag_path(hashtag.id)%></p>
                            <%end%>
                                            </div>
                                                </div>
                                              <%end%>
                                                  </div>

app/views/hashtags/edit.html.erb
<h1>Editing hashtag</h1>

<%= render "form", hashtag: @hashtag %>

<br>

<div>
  <%= link_to "Show this hashtag", @hashtag %> |
  <%= link_to "Back to hashtags", hashtags_path %>
</div>

app/views/hashtags/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Hashtags</h1>

<div class="row row-cols-1 row-cols-md-3 g-4">


  <% @hashtags.each do |hashtag| %>
    <%= render hashtag %>
  <% end %>

</div>

<%= link_to "New hashtag", new_hashtag_path %>

app/views/hashtags/new.html.erb
<h1>New hashtag</h1>

<%= render "form", hashtag: @hashtag %>

<br>

<div>
  <%= link_to "Back to hashtags", hashtags_path %>
</div>

app/views/hashtags/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @hashtag %>
<%if @hashtag.mytweets.length > 0%>
<ul>
<%@hashtag.mytweets.each do |tweet|%>
  <li><%=tweet.content%></li>

<%end%>
</ul>
<%else%>
  <p>vous n'avez pas encore tweeté avec ce hashtag</p>
<%end%>

<p></p>
<%=render "mytweets/form",mytweet:Mytweet.new(hashtag_id:@hashtag.id,content:["#",@hashtag.name].join)%>
<div>
  <%= link_to "Edit this hashtag", edit_hashtag_path(@hashtag) %> |
  <%= link_to "Back to hashtags", hashtags_path %>

  <%= button_to "Destroy this hashtag", @hashtag, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Petit Train De L'Espace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
              <a class="navbar-brand" href="#">Navbar</a>
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                          <span class="navbar-toggler-icon"></span>
                              </button>
                                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
                                          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                                    <li class="nav-item">
                                                                <a class="nav-link active" aria-current="page" href="/">Bienvenue</a>
                                                                        </li>
                                                                                <li class="nav-item">
                                                                                  <a class="nav-link" href="<%=hashtags_path%>">hashtags</a>
                                                                                                    </li>
                                                                                <li class="nav-item">
                                                                                  <a class="nav-link" href="<%=tweets_path%>">tweets</a>
                                                                                                    </li>
                                                                                <li class="nav-item">
                                                                                  <a class="nav-link" href="<%=users_path%>">users</a>
                                                                                                    </li>
                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                    </div>
    </nav>
    <%= yield %>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

app/views/mytweets/_form.html.erb
<%= form_with(model: mytweet) do |form| %>
  <% if mytweet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mytweet.errors.count, "error") %> prohibited this mytweet from being saved:</h2>

      <ul>
        <% mytweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_field :content %>
  </div>

  <div>
    <%= form.hidden_field :hashtag_id %>
  </div>

  <div>
    <%= form.hidden_field :tweet_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/mytweets/_mytweet.html.erb
<div id="<%= dom_id mytweet %>">
  <p>
    <strong>Content:</strong>
    <%= mytweet.content %>
  </p>

  <p>
    <strong>Hashtag:</strong>
    <%= mytweet.hashtag_id %>
  </p>

  <p>
    <strong>Tweet:</strong>
    <%= mytweet.tweet_id %>
  </p>

</div>

app/views/mytweets/_otherform.html.erb
<%= form_with(model: mytweet) do |form| %>
  <% if mytweet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mytweet.errors.count, "error") %> prohibited this mytweet from being saved:</h2>

      <ul>
        <% mytweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_field :content %>
  </div>

  <div>
    <%= form.label :myhashtag, style: "display: block" %>
    <%= form.text_field :myhashtag %>
  </div>

  <div>
    <%= form.hidden_field :tweet_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/mytweets/edit.html.erb
<h1>Editing mytweet</h1>

<%= render "form", mytweet: @mytweet %>

<br>

<div>
  <%= link_to "Show this mytweet", @mytweet %> |
  <%= link_to "Back to mytweets", mytweets_path %>
</div>

app/views/mytweets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Mytweets</h1>

<div id="mytweets">
  <% @mytweets.each do |mytweet| %>
    <%= render mytweet %>
    <p>
      <%= link_to "Show this mytweet", mytweet %>
    </p>
  <% end %>
</div>

<%= link_to "New mytweet", new_mytweet_path %>

app/views/mytweets/new.html.erb
<h1>New mytweet</h1>

<%= render "form", mytweet: @mytweet %>

<br>

<div>
  <%= link_to "Back to mytweets", mytweets_path %>
</div>

app/views/mytweets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @mytweet %>

<div>
  <%= link_to "Edit this mytweet", edit_mytweet_path(@mytweet) %> |
  <%= link_to "Back to mytweets", mytweets_path %>

  <%= button_to "Destroy this mytweet", @mytweet, method: :delete %>
</div>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_field :content %>
  </div>

  <div>
    <%= form.hidden_field :hashtag_id %>
  </div>

  <div>
    <%= form.hidden_field :tweet_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div id="<%= dom_id tweet %>">
  <p>
    <strong>Content:</strong>
    <%= tweet.content %>
  </p>

  <p>
    <strong>Hashtag:</strong>
    <%= tweet.hashtag_id %>
  </p>

  <p>
    <strong>Tweet:</strong>
    <%= tweet.tweet_id %>
  </p>

</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :fullname, style: "display: block" %>
    <%= form.text_field :fullname %>
  </div>

  <div>
    <%= form.label :pseudo, style: "display: block" %>
    <%= form.text_field :pseudo %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Fullname:</strong>
    <%= user.fullname %>
  </p>

  <p>
    <strong>Pseudo:</strong>
    <%= user.pseudo %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= user.image %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>
<%if @user.mytweets.length > 0%>
<ul>
<%@user.mytweets.each do |tweet|%>
  <li><%=tweet.content%></li>

<%end%>
</ul>
<%else%>
  <p>vous n'avez pas encore tweeté avec cet user</p>
<%end%>

<p></p>
<%=render "mytweets/otherform",mytweet:Mytweet.new(content:["@",@user.pseudo].join)%>
<div>


<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>

app/views/welcome/index.html.erb
<h1>Welcome</h1>
<p>bienvenue dans le petit train de l'espace</p>